site_name: iterate-webdev
repo_url: https://github.com/JohnTelford/iterate-webdev-venv

theme:
  name: material
  features:
    - toc.integrate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.prefetch.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top   
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - Home: index.md
  - Teams:
      - Team Define: team_define.md
      - Team Design: team_design.md
      - Team Develop: team_develop.md
      - Team Deploy: team_deploy.md
      - Team Maintenance: team_maintenance.md

copyright: Copyright &copy; 2024 John M. Telford
